# Lab 1: Python Basics

***
- **FIRST name: Moffat**:
- **LAST name: Muriithi**:
- **Student ID:**

Leave blank if individual:
- **Collaborator names**:
- **Collaborator student IDs**:
***

In today's lab, you will learn how to:

1.   navigate Jupyter notebooks;
2.   write and evaluate *expressions* in Python;
3.   call *functions* that other people have written;
4.   define and call *functions* you have written;
4.   break down and understand smaller parts of Python code.
5.   import code;
6.   what NumPy and Pandas are and how to use them;
7.   table operations;
8.   how to analyze data.



For this lab, you will need two datasets: <code>farmers_markets.csv</code> and <code>imdb.csv</code>. To upload them to your notebook, click on the **Upload Files** button on the left side of your screen.

### Instructions

- **Collaboration**: You must submit your own work. The collaboration policy for the labs is Consultation Collaboration. You may verbally discuss concepts with your classmates, without exchanging written text, code, or detailed advice. You must develop your own solution and submit your own work. All sources of information used including books, websites, students you talked to, must be cited in the submission. Please see the course FAQ document for details on this collaboration policy. We will adhere to current Faculty of Science guidelines on dealing with suspected cases of plagiarism.
- **Software**: We highly recommend that students use Syzygy for completing labs and assignments. This is the software used by the TAs in the course, and we can guarantee that there will be no issues with incompatible environments or imports.
- **Filling out the Notebook**: You must use this notebook to complete your lab. You will execute the questions in the notebook. The questions might ask for a short answer in text form or for you to write and execute a piece of code. Make sure you enter your answer in either case only in the cell provided.
- **Important**:  Do not use a different cell, do not delete cells, and do not create a new cell. Creating new cells for your code is not compatible with the auto-grading system we are using and thus your assignment will not get grading properly and you will lose marks for that question. As a reminder you must remove the raise NotImplementedError() statements from each question when answering.
- **Rules for Datasets**: Any datasets used in the lab cannot be imported from cloud storage, e.g google drive, and must be read from a file either on your local computer or uploaded to the google colab notebook. Importing from cloud storage will result in a zero.
- **Submission Formatting**: When you are done, you will submit your work from the notebook. Make sure to save your notebook before running it, and then submit on Canvas the notebook file with your work completed. Name your file with an L followed by the lab number (ex: L1.ipynb). Failure to do so will result in a zero! Finally your name must be written at the top of the lab or assignment document.

# 1. Google Colab notebooks
This webpage is called a Syzygy notebook. It uses a Jupyter environment to write and run code. It can also write text using a format called [Markdown](https://www.markdownguide.org/basic-syntax/).

## Text cells
Each block containing code or text is called a *cell*. To add a cell, hover your mouse above or below an existing cell and select which type you need.


<p> Text cells (like this one) can be edited by double-clicking on them. The window on the right shows you what the Markdown text will look like as you edit. </p>

## Code cells
<p> Other cells contain code in Python 3 language. Running a code cell will execute all of the code within it. </p>

To run a code cell, hover your mouse over the code. You will see a play button appear on the left side of the block. Either press this button, or hold down <code> shift </code> + <code> return </code> (macOS), or <code> shift </code> + <code> enter </code> (Windows).

<p> Try running this cell: </p>

In [6]:
print("Hello, World!")

Hello, World!

We can assign our message to a variable named <code>message</code>. To print the message, simply write the variable's name underneath.

In [7]:
message = "Hello World!"
message

'Hello World!'

**Question 1.1.** Fill in the code block below so that you print the message 'Welcome to CMPUT 200!'. Replace the line "<code>raise NotImplementedError()</code>" with your answer. Assign your symbols to the variable name <code>new_message</code>.

In [8]:
# YOUR CODE HERE
new_message = "Welcome to CMPUT 200!"

new_message

'Welcome to CMPUT 200!'

In [9]:
#TEST CELL: do not delete!

## Errors
<p> Python is a language and has rules just like any human language. As you code throughout the semester, you will become comfortable with the basic types of errors. </p>

Python's error documentation can be found [here](https://docs.python.org/3/tutorial/errors.html). You do not have to memorize every type of error, but it helps to be familiar with them when you're debugging.

A common type of error is called a <code>SyntaxError</code>. This happens when your code is missing a character, such as a parenthesis or a colon. In the code below, there is a missing parenthesis. Run the cell and see what happens.

In [10]:
print("This line has a SyntaxError!"

_IncompleteInputError: incomplete input (3378773658.py, line 1)

**Question 1.2.** How would you fix the error above? Replace the line "<code>raise NotImplementedError()</code>" with the correct code.

In [11]:
# YOUR CODE HERE
print("This line has a SyntaxError!")

This line has a SyntaxError!

# 2. Numbers
Data science largely deals with quantitative information. It is important to understand the two distinctions that Python makes between quantitavtive data: <code>int</code> and <code>float</code>.

- Integers are called <code>int</code> values in Python. This includes all whole numbers and their negative counterparts, as well as zero. These values have no decimal points.
- Real numbers are called <code>float</code> values in Python. They can represent whole numbers or numbers with a fractional component (negative, positive, or zero). They will always have a decimal point.

## Arithmetic

Programs are made of *expressions*, which tells the computer to combine two or more values using different operators. For example, <code>2 + 5</code> is an arithmetic expression which evaluates to <code>7</code>. The <code>+</code> symbol is called an *operator*. This is shown in the cell below.

In [12]:
2 + 5

7

Many basic arithmetic operations are built into Python. For example, to raise one number to the power of another number, the operator used is <code> ** </code>. For example, <code>2 ** 3</code> represents 2<sup>3</sup> which evaluates to 8.

In [13]:
2 ** 3

8

Python follows the order of operations (PEDMAS). Compare the outputs of the two cells below:

In [14]:
1 + 2 * 3 / 4 ** 5 - 6

-4.994140625

In [15]:
1 + (2 * 3 / 4) ** 5 - 6

2.59375

# 3. Names

In Python, we can quickly reference complicated concepts using one word. We do this with an *assignment statement*. An assignment statement has a name on the left side, followed by an <code>=</code> sign and an expression to be evaluated on the right.

In [16]:
nineteen = 5 * 2 + 9

When the cell above is executed, Python first computes the expression on the right side (<code>5 * 2 + 9</code>), which is 19. Next, it assigns the value to the name <code>nineteen</code>. After you run the cell, the value 19 is now bound to <code>nineteen</code>:

In [17]:
nineteen

19

**Question 3.1.** Try writing code that uses the name <code>ten</code>, which hasn't been assigned to anything yet. You should get a <code>NameError</code> error.

In [18]:
# YOUR CODE HERE
print(ten)

NameError: name 'ten' is not defined

We can include multiple expressions in one cell to compute intermediates:

In [19]:
semimonthly_salary = 841.25
monthly_salary = 2 * semimonthly_salary
number_of_months_in_a_year = 12
yearly_salary = number_of_months_in_a_year * monthly_salary
yearly_salary

20190.0

Names can contain letters and numbers, but it must start with a letter. Spaces are not allowed; instead, use the underscore character <code>_</code>. The name you choose must be decriptive enough to understand what is happening in your code, e.g. the code below is harder to understand:

In [20]:
a = 841.25
b = 2 * a
c = 12
d = c * b
d

20190.0

# 4. Calling functions

Python has [built-in functions](https://docs.python.org/3/library/functions.html) that make combining and manupulating values easier. These function perform like common operators.

<p> For example, the <code>abs</code> function takes a single argument and returns its absolute value: </p>

In [21]:
abs(2)

2

In [22]:
abs(-2)

2

**Question 4.1.** Explore the site linked above. How would you add the numbers <code>1, 15, 789, -46, 78, 3, 190, -394</code> together only using one function? Assign your answer to the name <code>add_numbers</code>.

In [23]:
numbers = [1, 15, 789, -46, 78, 3, 190, -394]

# YOUR CODE HERE
add_numbers = sum(numbers)

add_numbers

636

In [24]:
#TEST CELL: do not delete!

#### Multiple arguments
Some functions take in multiple arguments, separated by commas. For example, the <code>max</code> function returns the maximum argument. Notice how expressions can be used as arguments (<code>16 + 7</code>).

In [25]:
max(4, -68, 16 + 7, 6)

23

# 5. Nested expressions

 In the last example, we saw that functions can contain expressions. This is called a *nested expression*. These expressions can look complicated, but we can break it down into smaller pieces just like we would for a math problem.

 <p> Suppose we want to calculate how much someone's height deviates from average. Let the average human height be 1.70m, and an individual's height be 1.45m. To calculate the difference between the two heights, we would compute |1.45 - 1.70|. In Python, this would look like: </p>

In [26]:
abs(1.45-1.70)

0.25

If we break this nested expression down, the argument is computed first: <code>1.45 - 1.70 = -0.25</code>. That value is then passed to the <code>abs</code> function: <code>abs(-0.25)</code>. The final value returned is <code>0.25</code>.

**Question 5.1.** Say another individual's height is 2.12m. How would you use the <code>abs</code> function to compute the difference in average height? Use the name <code>distance_from_average</code> in your answer.

In [27]:
# YOUR CODE HERE
distance_from_average = abs(2.12-1.70)

distance_from_average

0.42000000000000015

In [28]:
#TEST CELL: do not delete!

## More nesting

Now say that we want to compute the largest difference between the two heights. To do that, we can use the <code>max</code> function along with the <code>abs</code> function. Run the cell below to see how this is done.

In [29]:
height_1 = 1.45
height_2 = 2.12
average_height = 1.70

largest_difference = max(abs(height_1-average_height), abs(height_2-average_height))

largest_difference

0.42000000000000015

Try breaking down this nested expression just like how we did above for <code>abs(1.45-1.70)</code>

**Question 5.2.** Given the heights of players from the Golden State Warriors, write an expression that computes the smallest difference between the three heights. Your expression shouldn't have any numbers in it, only function calls and the names klay, steph, and dangelo. Give the value of your expression the name <code>min_height_difference</code>. Try looking [here](https://docs.python.org/3/library/functions.html) again if you get stuck.

In [30]:
# the three players' heights in meters
klay = 2.01
steph = 1.91
dangelo = 1.95

# YOUR CODE HERE
min_height_difference = min(abs(klay - steph), abs(klay - dangelo), abs(steph - dangelo))

min_height_difference

0.040000000000000036

In [31]:
#TEST CELL: do not delete!

# 6. User defined Functions


Earlier, we learned that Python has built in functions, such as <code>abs</code> and <code>max</code> that make writing code easier. We can also write our own functions that we can call later in our code.

<p> Let's make a function that adds two numbers. To do this, we have to understand the different parts of a function: </p>

#### <code>def</code>
Functions always start with <code>def</code> (short for **def**ine):

> def

#### Name
The name is what we want to call our function. The same rules that apply to naming variables apply to naming functions. Let's name our function <code>number_sum</code>.

>def number_sum

#### Signature
The signature tells Python how many arguments your function has and what names you'll refer to those arguments in the function's code. A function can have any number of arguments and are always inclosed with round brackets. <code>number_sum</code> should take in two arguments, which we'll name <code>a</code> and <code>b</code>.

>def number_sum(a, b)

The arguments are always followed by a colon. This tells Python that the next lines are the body of the function. Python automatically indents these lines for us.

>def number_sum(a, b):

#### Body

The body contains the code that will be run when the function is called. Every line in the body must be indented or else it will not be considered a part of the function. When writing the body of a function, we generally only use the variables in the signature; if we want to use a variable outside of the function, we should define it in the signature!

<p> Finally, it's useful to include some documentation that describes what the function does. This makes it easier for others who are reading our code to understand what we're doing. Documentation usually uses a triple-quoted string. </p>

>def number_sum(a, b):
>>"""Sums numbers a and b"""
>><p> two_sum = a + b </p>

#### <code>return</code>
If you expect your function to return a value, then the last line of your body should always be a <code>return</code> statement. Once Python encounters a <code>return</code>, it stops executing the code in the function, so it makes sense to only have it at the end. If your function does not have a <code>return</code> statement, it will not return anything.

>def number_sum(a, b):
>>"""Sums numbers a and b"""
>><p> two_sum = a + b </p>
>> <p> return two_sum </p>

**Note**: If we don't use a <code>return</code> in our function, there are other statements we can use, such as the <code>print</code> statement. If we use <code>print</code>, the value will be printed to the console. <code>return</code> and <code>print</code> are **very** different: the value that is passed to <code>print</code> cannot be used outside of the function.

<p> Let's go through an example of calling our function: </p>

<p> If we call <code>number_sum(1, 2)</code>, the argument <code>a</code> in our signature will be assigned to 1, while the argument <code>b</code> in our signature will be assigned to 2. </p>

<p> Our definition will be ignored since it's in quotes. Next, the expression <code>two_sum = a + b</code> will be evaluated as <code>two_sum = 1 + 2</code>. </p>

Finally, the value of <code>two_sum</code> will be returned, which is three. Once the <code>return</code> statement is finished, Python will stop executing the code inside the function block and will resume executing any other code that we may have.

**Question 6.1.** Define <code>number_sum</code> in the cell below. Instead of summing two numbers, the signature will include a third number called <code>c</code>. Change the body of the function so that it adds three numbers instead of two.

In [32]:
def number_sum(a, b, c):
    # YOUR CODE HERE
    sum_of_three = a + b + c
    return sum_of_three

Run the cell below to test your function. The built-in function <code>assert</code> checks to see the the return value of your function is correct. You will get an error message if your function is wrong. If your function is correct, you shouldn't get any output. There are hidden tests to check other cases so don't hardcode the answer!

In [33]:
#TEST CELL: do not delete!
### TESTS
assert(number_sum(5, 7, 10) == 22)

You can use built-in functions (abs, min, etc) just like you did in previous labs.

**Question 6.2.** Suppose you have three sets of numbers and you want to add the smallest number of each set together. Use the <code>min</code> function and your function defined above to compute this. Assign your answer to <code>set_sum</code>.

*Hint* : start by finding the smallest number in each set, then call the function you made above. </p>
*Note* : you do not have to re-define <code>number_sum</code>! Like other variables, functions don't go away after you define them.</p>

In [34]:
set1 = (62, 4, 79, 6)
set2 = (23, 54, 16, 11)
set3 = (100, 45, 8, 15)

# YOUR CODE HERE
set1_min = min(set1)
set2_min = min(set2)
set3_min = min(set3)

set_sum = number_sum(set1_min, set2_min, set3_min)

set_sum

23

In [35]:
#TEST CELL: do not delete!

Some more notes about functions:

*   The names defined within a function body are only accessible within the function. Once the function is finished executing, every variable that was defined no longer exists. For example, the variable <code>two_sum</code> that we defined above is not accessible outside the function (unless we return it).
*   Functions can also take strings, arrays, or tables as arguments and can return them too.

# 7. Importing code

Most of the programming that we will do in this course will involve work that's already been done before. In this case, it's handy to rely on others' published code rather than writing it all ourselves. Rather than copying and pasting, Python allows us to import **modules**. A module is a file with Python code that contains defined variables and functions. By importing a module, we can use its code in our own notebook.

A common module that's used in data science is the <code>math</code> module. Suppose we want to accurately calculate the circumference of a circle. For π, we can use the math module, which already has pi defined for us:

In [36]:
import math
radius = 4
circumference_circle = 2 * radius * math.pi
circumference_circle

25.132741228718345

<p> In the code above, we access the module using the line <code>import math</code>. We can then use any function or variable defined within <code>math</code> by typing the name of the module folllowed by a dot, followed by the name of the variable or function that we want. </p>

<code> (module name).(name) </code>

**Question 7.1.** The module <code>math</code> also provides the name e for the base of the natural logarithm, which is roughly 2.71. Compute e<sup>π</sup>-π giving it the name <code>near_twenty</code>.

In [37]:
# YOUR CODE HERE
import math
near_twenty = math.pow(math.e,math.pi) - math.pi


near_twenty

19.99909997918947

In [38]:
#TEST CELL: do not delete!

## Accessing functions

In the question above, you used variables from the <code>math</code> module.

<p> Modules also define functions. For example, <code>math</code> defines the name <code>cos</code> for the cos function. Since we've already imported <code>math</code>, we can write <code>math.cos(1)</code> to compute the cos of 1 (note that this cos function assumes its argument to be in radians). </p>

 **Question 7.2.** A $\frac{\pi}{4}$-radian (45 degree) angle forms at a right triangle with equal base and height. If the hypotenuse is 1, then the base is cos($\frac{\pi}{4}$). Compute the value of cos($\frac{\pi}{4}$) using <code>cos</code> and <code>pi</code> from the <code>math</code> module below. Assign your answer the name <code>cos_pi_over_four</code>.

In [39]:
# YOUR CODE HERE
cos_pi_over_four = math.cos((math.pi)/4)

cos_pi_over_four

0.7071067811865476

In [40]:
#TEST CELL: do not delete!

Different functions take in a different number of arguments. Refer to this [documentation](https://docs.python.org/3/library/math.html) for all of the functions provided by <code>math</code> and how to use them.

# 8. Using NumPy and Pandas

NumPy and Pandas are two very popular libraries in Python that are largely used for data science. Pandas helps when working with large amounts of data. It provides us with a data structure called a <code>DataFrame</code>, which is like a table or spreadsheet. The rows and columns in a DataFrame are indexed so that we can perform operations on them.

<p> NumPy is a dependency of Pandas. Its main purpose is to perform calculations and manipulations on large sets of data. </p>

The table <code>farmers_markets.csv</code> contains data on farmers' markets in the United States. Each row represents an individual market.

<p> The following cell imports NumPy and Pandas as np and pd respectively. The last line loads the csv file and creates a DataFrame named <code>farmers_market</code>. </p>

In [41]:
import numpy as np
import pandas as pd

farmers_markets = pd.read_csv('farmers_markets.csv')

**Question 8.1.** Use the method <code>head</code> to display the first 5 rows of <code>farmers_market</code>. You can read the documentation [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html).

In [42]:
# YOUR CODE HERE
df = pd.DataFrame(farmers_markets)
df.head(5)

,FMID,MarketName,street,city,County,State,zip,x,y,Website,...,SFMNP,SNAP,Season1Date,Season1Time,Season2Date,Season2Time,Season3Date,Season3Time,Season4Date,Season4Time
0,1012063,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,05828,-72.140305,44.411013,https://sites.google.com/site/caledoniafarmers...,...,Y,N,06/08/2016 to 10/12/2016,Wed: 9:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
1,1011871,Stearns Homestead Farmers' Market,6975 Ridge Road,Parma,Cuyahoga,Ohio,44130,-81.728597,41.375118,http://Stearnshomestead.com,...,Y,Y,06/25/2016 to 10/01/2016,Sat: 9:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
2,1011878,100 Mile Market,507 Harrison St,Kalamazoo,Kalamazoo,Michigan,49007,-85.574887,42.296024,http://www.pfcmarkets.com,...,Y,Y,05/04/2016 to 10/12/2016,Wed: 3:00 PM-7:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
3,1009364,106 S. Main Street Farmers Market,106 S. Main Street,Six Mile,NaN,South Carolina,29682,-82.818700,34.804200,http://thetownofsixmile.wordpress.com/,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1010691,10th Steet Community Farmers Market,10th Street and Poplar,Lamar,Barton,Missouri,64759,-94.274619,37.495628,NaN,...,N,N,04/02/2014 to 11/30/2014,Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN

Notice how some values are 'NaN'. This means that the value is missing or it's not applicable.

### Columns & Rows

We can find the number of columns that a dataset has by using <code>len</code> (short for length) and <code>.columns</code>:

In [43]:
num_farmers_columns = len(farmers_markets.columns)
num_farmers_columns

59

**Question 8.2.** Find the number of rows that <code>farmers_markets</code> has by using similar functions as the ones above. Assign your answer to <code>num_farmers_rows</code>.  

*Hint*: <code>.rows</code> does not exist like it does for columns since the number of rows is really just the length of the dataset! </p>

In [44]:
# YOUR CODE HERE
num_farmers_rows = len(farmers_markets)

print("The table has", num_farmers_rows, "rows in it")

The table has 8546 rows in it

In [45]:
#TEST CELL: do not delete!

### Selecting

Sometimes, datasets will contain columns that we don't need in our analysis. In this case, we use square brackets around the columns that we want to keep. This creates a new table.

In [46]:
farmers_markets_locations = farmers_markets[["MarketName", "State"]]
farmers_markets_locations

                                            MarketName           State
0      Caledonia Farmers Market Association - Danville         Vermont
1                    Stearns Homestead Farmers' Market            Ohio
2                                      100 Mile Market        Michigan
3                    106 S. Main Street Farmers Market  South Carolina
4                  10th Steet Community Farmers Market        Missouri
...                                                ...             ...
8541                    Zia Bernalillo Farmers' Market      New Mexico
8542                          Zimmerman Farmers Market       Minnesota
8543                        Zion Canyon Farmers Market            Utah
8544                         Zionsville Farmers Market         Indiana
8545                         Zona Rosa Farmers' Market        Missouri

[8546 rows x 2 columns]

Notice how there are two sets of brackets when selecting multiple columns. If we only wanted to select one column, we would only need one set of brackets.

**Question 8.3.** Suppose we want to display market locations using coordinates instead of states. Create a table with only <code>MarketName</code>, longitude <code>x</code>, and latitude <code>y</code>. Assign your table to <code>farmers_markets_coords</code>.

In [47]:
# YOUR CODE HERE
farmers_markets_coords = farmers_markets[["x", "y"]]

farmers_markets_coords

               x          y
0     -72.140305  44.411013
1     -81.728597  41.375118
2     -85.574887  42.296024
3     -82.818700  34.804200
4     -94.274619  37.495628
...          ...        ...
8541 -106.546840  35.313704
8542  -93.585014  45.437700
8543 -113.003311  37.184508
8544  -86.261200  39.949100
8545  -94.580864  39.246317

[8546 rows x 2 columns]

In [48]:
#TEST CELL: do not delete!

We can also select the markets that are located in California only. The <code>==</code> symbol is called a *comparison operator*. In this case, the comparison operator looks at every value in the State column and only adds it to the DataFrame if it's equal to California.

In [49]:
california_farmers_markets = farmers_markets[farmers_markets['State'] == 'California']
california_farmers_markets

,FMID,MarketName,street,city,County,State,zip,x,y,Website,...,SFMNP,SNAP,Season1Date,Season1Time,Season2Date,Season2Time,Season3Date,Season3Time,Season4Date,Season4Time
88,1005272,Adelanto Stadium Farmers Market,Hwy 395 & Rancho Drive,Victorville,San Bernardino,California,92392,-117.405000,34.559300,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,1009019,Alameda Farmers' Market,Haight and Webster St.,Alameda,Alameda,California,NaN,-122.276762,37.774248,http://www.pcfma.com,...,N,N,01/01/2013 to 12/31/2013,Tue: 9:00 AM-1:00 PM;Sat: 9:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
130,1008835,Alisal Certified Farmers' Market,632 East Alisal Street,Salinas,Monterey,California,93905,-121.634178,36.673319,http://www.everyonesharvest.org,...,Y,Y,06/28/2016 to 10/11/2016,Tue: 11:00 AM-4:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
156,1009998,Altadena Farmers' Market,600 W. Palm Street,Altadena,Los Angeles,California,91001,-118.158130,34.200379,http://www.altadenafarmersmarket.com,...,Y,Y,01/08/2014 to 03/05/2014,Wed: 3:00 PM-7:00 PM;,03/12/2014 to 11/05/2014,Wed: 4:00 PM-8:00 PM;,11/12/2014 to 12/31/2014,Wed: 3:00 PM-7:00 PM;,NaN,NaN
162,1011421,Alum Rock Village Farmers' Market,57 North White Road,San Jose,Santa Clara,California,NaN,-121.833288,37.367770,http://www.pcfma.org,...,N,Y,01/01/2015 to 12/31/2015,Sun: 8:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8528,1001103,Yountville Farmers Market,Compadres Parking Lot-6539 Washington Street,Yountville,Napa,California,94599,-122.363000,38.402900,http://www.commongreens.com,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8533,1011920,Yreka Community Certified Farmers Market,1455 South Main Street,Yreka,Siskiyou,California,96097,-122.642124,41.712825,http://siskiyoufoodbank.org,...,Y,Y,06/15/2016 to 10/19/2016,Wed: 11:00 AM-2:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8534,1003731,Yuba City Certified Farmers Market-Saturday,Town Square On Plumas St. Between B St. & C St.,Yuab City,Sutter,California,95991,-121.613835,39.133181,NaN,...,Y,Y,April to October,Sat:8:00 AM - 12:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8535,1009912,Yuba City Downtown Certified Farmers Market,732 Plumas Street,Yuba City,Sutter,California,95991,-121.616935,39.138392,http://www.yubacitydowntown.com,...,Y,Y,05/01/2014 to 11/06/2014,Thu: 4:00 PM-8:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8536,1002380,Yucaipa CFM,California Street & Yucaipa Blvd.,Yucaipa,San Bernardino,California,92399,-117.039000,34.033900,http://www.yucaipamarketnight.com,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Drop

<p> The <code>drop</code> method is similar to selecting, but it takes away the columns that are provided. <code>drop</code> also creates a new table. </p>

Suppose we did not want <code>FMID</code> and <code>updateTime</code> in our <code>farmers_markets</code> table:

In [50]:
farmers_markets_without_fmid = farmers_markets.drop(columns = ["FMID", "updateTime"])
farmers_markets_without_fmid

,MarketName,street,city,County,State,zip,x,y,Website,Facebook,...,SFMNP,SNAP,Season1Date,Season1Time,Season2Date,Season2Time,Season3Date,Season3Time,Season4Date,Season4Time
0,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,05828,-72.140305,44.411013,https://sites.google.com/site/caledoniafarmers...,https://www.facebook.com/Danville.VT.Farmers.M...,...,Y,N,06/08/2016 to 10/12/2016,Wed: 9:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
1,Stearns Homestead Farmers' Market,6975 Ridge Road,Parma,Cuyahoga,Ohio,44130,-81.728597,41.375118,http://Stearnshomestead.com,NaN,...,Y,Y,06/25/2016 to 10/01/2016,Sat: 9:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
2,100 Mile Market,507 Harrison St,Kalamazoo,Kalamazoo,Michigan,49007,-85.574887,42.296024,http://www.pfcmarkets.com,https://www.facebook.com/100MileMarket/?fref=ts,...,Y,Y,05/04/2016 to 10/12/2016,Wed: 3:00 PM-7:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
3,106 S. Main Street Farmers Market,106 S. Main Street,Six Mile,NaN,South Carolina,29682,-82.818700,34.804200,http://thetownofsixmile.wordpress.com/,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10th Steet Community Farmers Market,10th Street and Poplar,Lamar,Barton,Missouri,64759,-94.274619,37.495628,NaN,NaN,...,N,N,04/02/2014 to 11/30/2014,Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8541,Zia Bernalillo Farmers' Market,335 S. Camino del Pueblo,Bernalillo,Sandoval,New Mexico,NaN,-106.546840,35.313704,http://www.eatfreshnm.org/,https://www.facebook.com/farmersmarketsnm?ref=hl,...,Y,Y,07/04/2014 to 10/24/2014,Fri: 4:00 PM-7:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8542,Zimmerman Farmers Market,"Lions Park, Main Street",Zimmerman,Sherburne,Minnesota,55398,-93.585014,45.437700,http://www.pzfarmersmarket.org,princeton-zimerman farmers market,...,N,N,06/07/2016 to 10/04/2016,Tue: 2:30 AM-6:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8543,Zion Canyon Farmers Market,1212 Zion Park Blvd.,Springdale,Washington,Utah,84767,-113.003311,37.184508,http://www.zionharvest.org,https://www.facebook.com/ZionCanyonFarmersMark...,...,N,N,04/25/2015 to 10/17/2015,Sat: 9:00 AM-12:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8544,Zionsville Farmers Market,Hawthorne & Main Street,Zionsville,Boone,Indiana,46077,-86.261200,39.949100,http://www.zionsvillefarmersmarket.org,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8545,Zona Rosa Farmers' Market,Off of I-29 and Barry Road,Kansas City,Platte,Missouri,64153,-94.580864,39.246317,NaN,NaN,...,N,N,06/01/2015 to 09/30/2015,Tue: 4:00 PM-8:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN

**Question 8.4.** Create a table that does not contain the <code>Website</code>, <code>Facebook</code>, <code>Twitter</code>, <code>Youtube</code>, and <code>OtherMedia</code> columns. Assign your table to <code>farmers_markets_without_media</code>.

In [51]:
# YOUR CODE HERE
farmers_markets_without_media = farmers_markets.drop(columns = ["Website", "Facebook", "Twitter", "Youtube", "OtherMedia"])
farmers_markets_without_media

,FMID,MarketName,street,city,County,State,zip,x,y,Organic,...,SFMNP,SNAP,Season1Date,Season1Time,Season2Date,Season2Time,Season3Date,Season3Time,Season4Date,Season4Time
0,1012063,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,05828,-72.140305,44.411013,Y,...,Y,N,06/08/2016 to 10/12/2016,Wed: 9:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
1,1011871,Stearns Homestead Farmers' Market,6975 Ridge Road,Parma,Cuyahoga,Ohio,44130,-81.728597,41.375118,-,...,Y,Y,06/25/2016 to 10/01/2016,Sat: 9:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
2,1011878,100 Mile Market,507 Harrison St,Kalamazoo,Kalamazoo,Michigan,49007,-85.574887,42.296024,N,...,Y,Y,05/04/2016 to 10/12/2016,Wed: 3:00 PM-7:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
3,1009364,106 S. Main Street Farmers Market,106 S. Main Street,Six Mile,NaN,South Carolina,29682,-82.818700,34.804200,-,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1010691,10th Steet Community Farmers Market,10th Street and Poplar,Lamar,Barton,Missouri,64759,-94.274619,37.495628,-,...,N,N,04/02/2014 to 11/30/2014,Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8541,1004767,Zia Bernalillo Farmers' Market,335 S. Camino del Pueblo,Bernalillo,Sandoval,New Mexico,NaN,-106.546840,35.313704,-,...,Y,Y,07/04/2014 to 10/24/2014,Fri: 4:00 PM-7:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8542,1000778,Zimmerman Farmers Market,"Lions Park, Main Street",Zimmerman,Sherburne,Minnesota,55398,-93.585014,45.437700,N,...,N,N,06/07/2016 to 10/04/2016,Tue: 2:30 AM-6:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8543,1002868,Zion Canyon Farmers Market,1212 Zion Park Blvd.,Springdale,Washington,Utah,84767,-113.003311,37.184508,N,...,N,N,04/25/2015 to 10/17/2015,Sat: 9:00 AM-12:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8544,1004686,Zionsville Farmers Market,Hawthorne & Main Street,Zionsville,Boone,Indiana,46077,-86.261200,39.949100,-,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8545,1011418,Zona Rosa Farmers' Market,Off of I-29 and Barry Road,Kansas City,Platte,Missouri,64153,-94.580864,39.246317,-,...,N,N,06/01/2015 to 09/30/2015,Tue: 4:00 PM-8:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
#TEST CELL: do not delete!

### Sort

<p> We can sort the contents of a desired column using the <code>sort_values</code> method. </p>

When using sort, keep these points in mind:

1.   The of the first argument is the name of the column that's being sorted
2.   If the column has text in it, its contents will be sorted alphabetically. If the column has numbers in it, its contents will be sorted numerically
3.   <code>sort_values</code> makes a new table (the contents of the original table will not be sorted)
4.   Rows will always stick together when a column is being sorted.

For example, suppose we wanted to sort the markets in alphabetical order by city:

In [53]:
farmers_markets_state_sorted = farmers_markets.sort_values(by = ["city"])
farmers_markets_state_sorted

,FMID,MarketName,street,city,County,State,zip,x,y,Website,...,SFMNP,SNAP,Season1Date,Season1Time,Season2Date,Season2Time,Season3Date,Season3Time,Season4Date,Season4Time
2911,1009174,Garden Station Sunday Market,509 East 4th Street,Dayton,NaN,Ohio,45402,-84.185400,39.759300,http://www.daytongardenstation.org,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7323,1009183,Terra Local,Park st and Eagle Street,Geneva,NaN,Ohio,NaN,-80.950100,41.803700,http://www.terralocal.net/,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3317,1003781,Harrington Farmers Market,Commerce St. & Clark St.,Harrington,NaN,Delaware,19952,-75.578200,38.923600,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7777,1005967,"Urban Farmer's Market (Madison, FL)",College Loop Behind O'neals Resturant,Madison,Madison,Florida,32340,-83.422333,30.471328,NaN,...,N,N,05/01/2014 to,Fri: 9:00 AM-3:00 PM;Sat: 9:00 AM-3:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
7917,1009377,Vliet Street Green Market,4420 W Vliet Street,Milwaukee,NaN,Wisconsin,53208,-87.969500,43.048900,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6883,1004809,South Bronx Community Farmers Market,E. 146th Street & St. AnnNULLs Ave.,NaN,Bronx,New York,NaN,-73.914100,40.812300,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7123,1008425,Stone County Locally Grown Online Market,www.stonecounty.locallygrown.net,NaN,Stone,Arkansas,NaN,-92.117652,35.868408,NaN,...,N,N,01/01/2013 to 12/31/2013,Tue: -9:00 PM;Sun: 1:00 PM-;,NaN,NaN,NaN,NaN,NaN,NaN
7473,1005768,The Olde Farmers Market / Springville,Mechanic Street,NaN,Erie,New York,NaN,-78.666100,42.508600,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8430,1006510,Winter Sun Farms New Paltz Market,Broadhead Avenue,NaN,Ulster,New York,NaN,-74.085600,41.761200,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8431,1006511,Winter Sun Farms Vassar Market,Chapin Ave. and Dutchess Ave.,NaN,Dutchess,New York,NaN,-74.099900,40.596100,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

If we wanted to sort by reverse alphabetical order, we would include <code>ascending=False</code> as an argument:

In [54]:
farmers_markets_state_sorted = farmers_markets.sort_values(by = ["city"], ascending=False)
farmers_markets_state_sorted

,FMID,MarketName,street,city,County,State,zip,x,y,Website,...,SFMNP,SNAP,Season1Date,Season1Time,Season2Date,Season2Time,Season3Date,Season3Time,Season4Date,Season4Time
8468,1005885,Woodstock Farmers Market,1102 McConnell Road,woodstock,McHenry,Illinois,60098,-88.430380,42.305584,http://www.woodstockfarmersmarket.org,...,Y,Y,11/02/2013 to 12/21/2013,Sat: 9:00 AM-12:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8467,1005884,Woodstock Farmers Market,100 Johnson Street,woodstock,McHenry,Illinois,60098,-88.447680,42.314782,http://www.woodstockfarmersmarket.org,...,Y,Y,05/03/2014 to 10/28/2014,Tue: 8:00 AM-1:00 PM;Sun: 8:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
8290,1003961,Wheatland Farmers' Market,713 9th,wheatland,Platte,Wyoming,82201,-104.953257,42.054552,NaN,...,Y,N,07/13/2013,Sat: 8:00 AM-10:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
7919,1010492,Volcano Farmers Market,14-4030 wright road,volcano,Hawaii,Hawaii,96785,-155.249290,19.464087,NaN,...,N,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7669,1002896,Tularosa Farmers Market,corner of bookout and central avenue,tularosa,Otero,New Mexico,88352,-106.010900,33.079660,NaN,...,Y,N,June to October,Sat:7:30 AM - 10:30 PM;,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6883,1004809,South Bronx Community Farmers Market,E. 146th Street & St. AnnNULLs Ave.,NaN,Bronx,New York,NaN,-73.914100,40.812300,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7123,1008425,Stone County Locally Grown Online Market,www.stonecounty.locallygrown.net,NaN,Stone,Arkansas,NaN,-92.117652,35.868408,NaN,...,N,N,01/01/2013 to 12/31/2013,Tue: -9:00 PM;Sun: 1:00 PM-;,NaN,NaN,NaN,NaN,NaN,NaN
7473,1005768,The Olde Farmers Market / Springville,Mechanic Street,NaN,Erie,New York,NaN,-78.666100,42.508600,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8430,1006510,Winter Sun Farms New Paltz Market,Broadhead Avenue,NaN,Ulster,New York,NaN,-74.085600,41.761200,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8431,1006511,Winter Sun Farms Vassar Market,Chapin Ave. and Dutchess Ave.,NaN,Dutchess,New York,NaN,-74.099900,40.596100,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Question 8.5.** Now, sort <code>farmers_markets</code> by **longitude (<code>x</code>)** in descending order. Assign your table to <code>farmers_markets_locations_by_longitude</code>.

In [55]:
# YOUR CODE HERE
farmers_markets_locations_by_longitude = farmers_markets.sort_values(by= ["x"], ascending = False)
farmers_markets_locations_by_longitude

,FMID,MarketName,street,city,County,State,zip,x,y,Website,...,SFMNP,SNAP,Season1Date,Season1Time,Season2Date,Season2Time,Season3Date,Season3Time,Season4Date,Season4Time
1284,1004972,"Christian ""Shan"" Hendricks Vegetable Market",Company Street,Saint Croix,Christiansted,Virgin Islands,NaN,-64.704300,17.744900,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4063,1004880,La Reine Farmers Market,Estate Body Slob,Saint Croix,Christiansted,Virgin Islands,NaN,-64.778900,17.732200,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,1004881,Anne Heyliger Vegetable Market,Queen Cross Street,Saint Croix,Frederiksted,Virgin Islands,NaN,-64.879900,17.709900,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6398,1004967,Rothschild Francis Vegetable Market,Charlotte Amalie,St. Thomas,St. Thomas,Virgin Islands,NaN,-64.932600,18.342800,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2650,1011914,Feria Agrícola de Luquillo,Centro de Arte y Cultura de Luquillo,Luquillo,Luquillo,Puerto Rico,00773,-65.720737,18.378202,http://www.luquillofarmersmarket.org,...,N,N,01/01/2016 to 12/31/2016,Sat: 8:00 AM-1:00 PM;,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3383,1007537,Hawaiian Farmers of Hanalei,5-5785 Kuhio Highway,Hanalei,Kauai,Hawaii,96714,-159.514000,22.203300,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3888,1001032,Kalaheo Neighborhood Center (Sunshine Markets),Paplina Road off Kaumualli,Kalaheo,Kauai,Hawaii,96741,-159.527000,21.925100,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3290,1003612,Hanapepe Park (Sunshine Markets),Old Hanapepe Town,Hanapepe,Kauai,Hawaii,96716,-159.588000,21.910100,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3924,1003613,Kekaha Neighborhood Center (Sunshine Markets),Elepaio Road,Kekaha,Kauai,Hawaii,96752,-159.718000,21.970400,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7617,1001903,Trapper Creek Farmers Market,Post Office parking lot,Trapper Creek,NaN,Alaska,99683,-166.540000,53.874800,NaN,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
#TEST CELL: do not delete!

# 9. Analyzing a dataset

<p> We are now going to use the concepts discussed above to analyze a new dataset. </p>  

Run the cell below to make a new DataFrame named <code>imdb</code>. The DataFrame contains the top 1000 highest-reated movies on IMDb. Notice the `.dropna()` function at the end, this removes all rows that contain NaN.

In [57]:
imdb = pd.read_csv("imdb.csv").dropna()
imdb.head(3)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

*Comparison operators* are used to filter our data so that we're only left with the values that we want. For example, the code <code>imdb[imdb['IMDB_Rating'] >= 6.5]</code> only includes ratings equal or greater than 6.5 in the DataFrame.

**Question 9.1.** Create a table of movies released between 2015 and 2020 inclusive with ratings above 7. The table should only include the columns <code>Released_Year</code>, <code>Series_Title</code>, and <code>IMDB_Rating</code> **in that order**.

*Hint*: you may create intermediate tables for each step that's needed, but make sure that your final table is assigned to <code>rating_over_7</code>. </p>

In [58]:
# YOUR CODE HERE
imdb_rating = imdb[imdb['IMDB_Rating'] > 7]
imdb_rating2 = imdb_rating[imdb_rating['Released_Year'] >= 2015]
imdb_rating3 = imdb_rating2[imdb_rating2['Released_Year'] <= 2020]
rating_over_7 = imdb_rating3[["Released_Year", "Series_Title", "IMDB_Rating"]]


#rating_over_7
rating_over_7

     Released_Year                       Series_Title  IMDB_Rating
19            2019                       Gisaengchung          8.6
33            2019                              Joker          8.5
53            2018                         Capharnaüm          8.4
56            2016                     Kimi no na wa.          8.4
58            2018  Spider-Man: Into the Spider-Verse          8.4
..             ...                                ...          ...
892           2016                              Moana          7.6
893           2015                            Sicario          7.6
894           2015                              Creed          7.6
896           2016                 Hell or High Water          7.6
903           2018                     A Star Is Born          7.6

[83 rows x 3 columns]

In [59]:
#TEST CELL: do not delete!

**Question 9.2.** Use the techniques mentioned above to calculate the *percent* of movies made in the 20th century (1900-1999) and the 21st century (2000 and later). Assign your answers to <code>percent_20th_century</code> and <code>percent_21st_century</code>. You do NOT have to round your answer.

*Hint*: The percent of movies release in the 20th century is the number of movies released between 1900-1999 divided by the total number of movies, times 100%.

In [60]:
# YOUR CODE HERE
total_movies = len(imdb)
movies_year = imdb[imdb['Released_Year'] > 1900]
movies_year2 = movies_year[movies_year['Released_Year'] < 1999]
percent_20th_century = ((len(movies_year2))/total_movies)*100

movies_year3 = imdb[imdb['Released_Year'] >= 2000]
percent_21st_century = ((len(movies_year3))/total_movies)*100


print("Percent released in 20th century:", percent_20th_century, "%")
print("Percent released in 21st century:", percent_21st_century, "%")

Percent released in 20th century: 44.460028050490884 %
Percent released in 21st century: 53.15568022440392 %

In [61]:
#TEST CELL: do not delete!

## Functions and tables

We will now write a function that uses the imdb.csv dataset. Run the cell below.

In [62]:
import pandas as pd
import numpy as np

movies = pd.read_csv("imdb.csv")

Suppose we want sort the list of movies by alphabetical order and return the first one for a specific year, say 1992. You might write something like this:

In [63]:
movies_1992 = movies[movies["Released_Year"] == 1992]
sorted_movies_1992 = movies_1992.sort_values(by='Series_Title')
first_alphabetical_movie_1992 = sorted_movies_1992.iloc[0]

hardcode_1992 = first_alphabetical_movie_1992
hardcode_1992

Poster_Link      https://m.media-amazon.com/images/M/MV5BMmRlZD...
Series_Title                                        A Few Good Men
Released_Year                                                 1992
Certificate                                                      U
Runtime                                                    138 min
Genre                                              Drama, Thriller
IMDB_Rating                                                    7.7
Overview         Military lawyer Lieutenant Daniel Kaffee defen...
Meta_score                                                    62.0
Director                                                Rob Reiner
Star1                                                   Tom Cruise
Star2                                               Jack Nicholson
Star3                                                   Demi Moore
Star4                                                  Kevin Bacon
No_of_Votes                                                 235388
Gross                                                  141,340,178
Name: 824, dtype: object

Note that <code>.iloc[0]</code> selects the first row of the data frame <code>sorted_movies_1992</code>. You can read more about <code>.iloc()</code> and <code>.loc()</code> [here](https://www.geeksforgeeks.org/difference-between-loc-and-iloc-in-pandas-dataframe/).

You might want to repeat this for multiple different years. However, it doesn't make sense to rewrite the same code multiple times, so instead you write a function.

**Question 10.1.** Write a function called <code>print_first_alphabetical_movie</code> that takes the year as its single argument.

In [ ]:
# YOUR CODE HERE
def print_first_alphabetical_movie(year):
    movies_year = movies[movies["Released_Year"] == year]
    sorted_movies_year = movies_year.sort_values(by='Series_Title')
    first_alphabetical_movie_1992 = sorted_movies_year.iloc[0]
    return first_alphabetical_movie_1992


# the code below makes a call to the function for the year 1992
function_1992 = print_first_alphabetical_movie(1992)
function_1992

The cell below tests to see if the title of the movie matches of the function matches the hardcoded version above.

In [ ]:
#TEST CELL: do not delete!
assert(function_1992.iloc[1] == hardcode_1992.iloc[1])

# Rubric

| Question | Points|
|----------|----------|
| 1.1.    | 5   |
| 1.2.    | 5   |
| 3.1.    | 5   |
| 4.1.    | 10   |
| 5.1.    | 10   |
| 5.2.    | 15   |
| 6.1     | 8    |
| 6.2     | 8    |
| 7.1.    | 3  |
| 7.2.    | 5   |
| 8.1.    | 2   |
| 8.2.    | 5  |
| 8.3.    | 5   |
| 8.4.    | 5   |
| 8.5.    | 5  |
| 9.1.    | 10   |
| 9.2.    | 10   |
| 10.1.   | 10   |
| Total:    | 128   |